
#define rr RGB(0x11,0x11,0x11)
#define ii RGB(0x22,0x22,0x22)
#define zz RGB(0x33,0x33,0x33)
#define WW RGB(0x44,0x44,0x44)
#define mm RGB(0x55,0x55,0x55)
#define ww RGB(0x66,0x66,0x66)
#define kk RGB(0x77,0x77,0x77)
#define XX RGB(0x88,0x88,0x88)
#define ss RGB(0x99,0x99,0x99)
#define oo RGB(0xaa,0xaa,0xaa)
#define VV RGB(0xbb,0xbb,0xbb)
#define yy RGB(0xcc,0xcc,0xcc)
#define qq RGB(0xdd,0xdd,0xdd)
#define GG RGB(0xee,0xee,0xee)
const unsigned short logo_start[]={
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,WW,WW,WW,mm,XX,XX,ww,WW,WW,ww,XX,ww,WW,WW,WW,kk,XX,mm,WW,WW,mm,kk,XX,ww,WW,WW,WW,WW, ww,WW,kk,XX,kk,WW,kk,XX,XX,XX,ww,WW,WW,ww,XX,XX,WW,WW,WW,mm,kk,XX,XX,ww,WW,WW,ww,XX,XX,XX,XX,XX,
 XX,XX,XX,oo,ss,XX,ss,WW,zz,ss,ww,oo,XX,rr,ww,yy,kk,ss,kk,rr,XX,oo,kk,ss,mm,rr,XX,yy,kk,ss,ss,WW, yy,WW,WW,XX,yy,ii,kk,XX,XX,XX,mm,ss,ss,ii,mm,yy,kk,ss,ss,ww,ii,XX,XX,mm,ss,ss,rr,mm,XX,XX,XX,XX,
 XX,XX,XX,oo,ss,mm,oo,yy,ii,qq,WW,mm,yy,yy,ww,qq,zz,oo,GG,WW,kk,yy,zz,oo,GG,WW,mm,qq,zz,XX,XX,XX, oo,oo,ii,XX,yy,zz,XX,XX,XX,yy,mm,ss,VV,yy,rr,yy,XX,ww,oo,qq,ii,ss,VV,ww,ss,yy,qq,ww,XX,XX,XX,XX,
 XX,XX,XX,oo,ss,rr,zz,XX,zz,VV,qq,ww,ii,rr,kk,qq,ii,ii,kk,WW,XX,yy,ii,XX,yy,kk,WW,qq,mm,mm,mm,ii, XX,GG,ii,oo,kk,mm,XX,XX,oo,oo,zz,XX,XX,qq,ii,yy,XX,ii,ii,ss,mm,VV,XX,WW,ss,ii,ii,zz,XX,XX,XX,XX,
 XX,XX,XX,oo,oo,oo,qq,yy,kk,ww,ww,yy,GG,ww,WW,qq,kk,qq,yy,ss,ss,yy,ii,XX,yy,kk,mm,qq,mm,yy,yy,ss, XX,yy,ww,ss,zz,kk,XX,XX,oo,oo,ii,XX,XX,qq,ii,yy,XX,VV,yy,zz,ww,VV,ss,zz,VV,GG,oo,ii,XX,XX,XX,XX,
 XX,XX,XX,oo,ss,WW,XX,XX,XX,qq,zz,zz,ww,kk,WW,qq,ii,XX,XX,XX,ss,yy,rr,WW,XX,zz,kk,qq,ii,WW,WW,WW, kk,oo,yy,ww,zz,XX,XX,ii,kk,GG,ii,zz,WW,ss,zz,yy,XX,WW,qq,ss,rr,ss,GG,rr,zz,WW,ss,ii,XX,XX,XX,XX,
 XX,XX,XX,oo,yy,mm,XX,XX,XX,oo,GG,oo,oo,oo,kk,GG,ww,XX,XX,XX,ss,GG,oo,oo,yy,XX,XX,GG,oo,oo,oo,kk, ww,XX,GG,oo,mm,XX,yy,ss,ww,VV,GG,oo,VV,VV,kk,yy,VV,mm,XX,GG,XX,ww,VV,GG,oo,VV,yy,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,ss,XX,XX,XX,XX,XX,XX,oo,ss,XX,XX,XX,XX,XX,XX,XX,XX,ss,ss,ss,XX,XX,XX,ss,ss,ss,ss,XX, XX,XX,XX,ss,XX,XX,XX,ss,XX,XX,XX,oo,ss,XX,XX,XX,ss,XX,XX,XX,ss,XX,XX,XX,oo,ss,XX,XX,XX,XX,XX,XX,

 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,

 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,GG,GG,GG,GG,GG,GG,GG,GG,GG,GG,GG,GG,XX,XX,XX,XX,XX,XX,XX,qq, qq,qq,qq,qq,qq,qq,qq,XX,XX,XX,yy,yy,yy,yy,yy,yy,yy,yy,yy,yy,yy,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,GG,XX,XX,XX,XX,XX,XX,XX,qq, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,yy,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,GG,XX,XX,XX,XX,XX,XX,XX,qq, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,yy,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,GG,XX,XX,XX,XX,XX,XX,XX,qq, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,yy,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,GG,GG,GG,GG,GG,GG,GG,GG,GG,GG,GG,GG,XX,XX,XX,XX,XX,XX,XX,qq, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,yy,yy,yy,yy,yy,yy,yy,yy,yy,yy,yy,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,GG,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,qq, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,yy,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,GG,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,qq, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,yy,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,GG,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,qq, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,yy,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,GG,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,qq,qq,qq,qq,qq,qq,qq,qq, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,yy,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,

 XX,XX,XX,mm,mm,mm,mm,XX,mm,mm,mm,mm,XX,XX,WW,WW,WW,WW,XX,WW,XX,WW,XX,XX,XX,XX,XX,zz,XX,XX,zz,XX, XX,XX,XX,XX,XX,XX,ii,XX,ii,XX,ii,XX,XX,XX,XX,rr,rr,rr,rr,rr,rr,rr,rr,rr,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,mm,XX,XX,mm,XX,mm,XX,XX,mm,XX,XX,XX,WW,XX,WW,XX,XX,WW,XX,WW,XX,XX,XX,zz,XX,XX,XX,zz,XX, XX,XX,XX,XX,ii,ii,XX,XX,ii,XX,ii,XX,XX,XX,XX,rr,XX,XX,XX,rr,XX,XX,XX,rr,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,mm,mm,mm,mm,XX,mm,mm,mm,mm,XX,XX,XX,XX,WW,XX,XX,XX,XX,WW,XX,XX,XX,zz,XX,XX,zz,zz,zz,zz, zz,zz,XX,XX,XX,ii,XX,ii,ii,ii,ii,ii,ii,XX,XX,rr,XX,rr,rr,rr,rr,rr,XX,rr,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,mm,XX,XX,XX,XX,XX,XX,XX,mm,XX,XX,WW,WW,WW,WW,WW,WW,WW,XX,WW,XX,XX,XX,zz,zz,XX,XX,zz,XX, XX,zz,XX,XX,ii,ii,ii,XX,ii,XX,ii,XX,XX,XX,XX,rr,rr,rr,rr,rr,rr,rr,rr,rr,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,mm,XX,mm,mm,mm,mm,mm,XX,mm,XX,XX,XX,XX,XX,WW,XX,WW,XX,XX,XX,XX,XX,XX,XX,zz,XX,XX,zz,XX, XX,zz,XX,XX,XX,ii,XX,XX,ii,ii,ii,ii,ii,XX,XX,rr,rr,rr,XX,XX,XX,rr,XX,rr,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,mm,XX,XX,mm,XX,mm,XX,XX,mm,XX,XX,WW,WW,WW,WW,WW,WW,WW,WW,WW,XX,XX,XX,zz,XX,zz,XX,zz,XX, XX,zz,XX,XX,ii,ii,ii,XX,ii,XX,ii,XX,XX,XX,XX,rr,XX,rr,rr,rr,rr,rr,XX,rr,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,mm,XX,mm,mm,mm,mm,mm,XX,mm,XX,XX,XX,XX,XX,WW,XX,WW,XX,XX,XX,XX,XX,zz,XX,XX,XX,zz,XX,XX, XX,zz,XX,XX,ii,ii,XX,XX,ii,ii,ii,ii,ii,XX,XX,rr,XX,XX,rr,rr,rr,XX,rr,rr,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,mm,XX,XX,mm,XX,mm,XX,XX,mm,XX,XX,XX,XX,WW,XX,XX,WW,XX,XX,WW,XX,XX,zz,zz,zz,zz,zz,XX,XX, XX,zz,XX,XX,XX,ii,XX,XX,ii,XX,ii,XX,XX,XX,XX,rr,XX,rr,XX,rr,XX,rr,XX,rr,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,mm,XX,mm,XX,XX,mm,XX,XX,mm,XX,XX,WW,WW,XX,XX,XX,WW,WW,WW,WW,XX,XX,XX,XX,XX,zz,XX,XX,zz, zz,XX,XX,XX,XX,ii,XX,XX,ii,ii,ii,ii,ii,XX,XX,rr,rr,rr,rr,rr,rr,rr,rr,rr,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,
 XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX, XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,XX,


};
#undef rr
#undef ii
#undef zz
#undef WW
#undef mm
#undef ww
#undef kk
#undef XX
#undef ss
#undef oo
#undef VV
#undef yy
#undef qq
#undef GG
